kind: pipeline
name: build monitoring

globals:
  - &tf_vars
    VERSION: 1.0.1
    
steps:
  - name: test1
    image: ubuntu:18.04
    environment:
      <<: *tf_vars
    commands:
      - echo $VERSION
      - VERSION="1.0.2"
      
  - name: test2
    image: ubuntu:18.04
    environment:
      <<: *tf_vars
    commands:
      - echo $VERSION
   
   
      
