kind: pipeline
name: build monitoring

environment:
  AZ_ACR_NAME: 
steps:
  - name: build image
    image: mcr.microsoft.com/azure-cli
    environment: 
      AZ_ACR_NAME:
        from_secret: AZ_ACR_NAME
      AZ_TENANT_ID:
        from_secret: AZ_TENANT_ID
      AZ_SUBSCRIPTION_ID: 
        from_secret: AZ_SUBSCRIPTION_ID
      ARM_CLIENT_ID:
        from_secret: ARM_CLIENT_ID
      ARM_CLIENT_SECRET:
        from_secret: ARM_CLIENT_SECRET
      RETRIES: 0
      MAX_RETRIES: 3
    commands:
   # - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $AZ_TENANT_ID
   # - az acr build -t sample/hello-world:{{$DRONE_BUILD_NUMBER}} -r $AZ_ACR_NAME .
    - until az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $AZ_TENANT_ID --output none || $RETRIES -ge $MAX_RETRIES; do echo "Waiting for service principal..."; RETRIES=$((RETRIES+1)); sleep 2; done
    - echo $RETRIES
