kind: pipeline
name: build monitoring

globals:
  - &tf_vars
    VERSION: 1.0.1
    
steps:
  - name: trivy image
    image: aquasec/trivy
    environment:
      <<: *tf_vars
    commands:
      - trivy image plugins/docker:19.03.8
      
  - name: dockle image
    image: goodwithtech/dockle
    environment:
      <<: *tf_vars
    commands:
      - dockle plugins/docker:19.03.8
   
   
      
