kind: pipeline
name: build monitoring

steps:
  - name: consume image
    image: swacr.azurecr.io/sample/hello-world
    commands: 
    - az --version
    - vault --version
    - terraform --version

image_pull_secrets:
- dockerconfigjson
