kind: pipeline
name: build monitoring

globals:
  - &tf_vars
    VERSION: 1.0.1
    
steps:
       
  - name: trivy image
    image: aquasec/trivy
    environment:
      <<: *tf_vars
    commands:
      - trivy image --exit-code 0 --severity LOW,MEDIUM,HIGH node:14.15.4
      - trivy image --exit-code 1 --severity CRITICAL node:14.15.4
     # - trivy fs .
      #- trivy image --exit-code 0 --severity LOW,MEDIUM,HIGH plugins/docker:19.03.8 
     # - trivy image --exit-code 1 --severity CRITICAL plugins/docker:19.03.8 
      #- trivy image --exit-code 0 --severity LOW,MEDIUM,HIGH -f json -o results01.json plugins/docker:19.03.8 
     # - trivy image --exit-code 1 --severity CRITICAL -f json -o results02.json plugins/docker:19.03.8
  
  - name: read file
    image: ubuntu:20.04
    environment:
      <<: *tf_vars
    commands:
     # - cat results01.json
     # - cat results02.json
      
      
      
   
   
      
