kind: pipeline
name: build monitoring

globals:
  - &tf_vars
    VERSION: 1.0.1
    
steps:
  - name: build image
    image: mcr.microsoft.com/azure-cli
    environment: 
      ARM_CLIENT_ID:
       from_secret: ARM_CLIENT_ID
      ARM_CLIENT_SECRET:
       from_secret: ARM_CLIENT_SECRET
      AZ_ACR_NAME:
       from_secret: AZ_ACR_NAME
      AZ_TENANT_ID:
       from_secret: AZ_TENANT_ID
      AZ_SUBSCRIPTION_ID: 
       from_secret: AZ_SUBSCRIPTION_ID
      RETRIES: 0
      MAX_RETRIES: 3
    commands:
       - DRONE_SEMVER_PATCH=$DRONE_BUILD_NUMBER
       - DRONE_SEMVER="drone$DRONE_SEMVER_PATCH"
       - echo $DRONE_SEMVER
       - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $AZ_TENANT_ID
       # - docker build -t "sample/hello-world:$DRONE_SEMVER" .
       - az acr build -t sample/sw-hello-world:"1.0.$DRONE_BUILD_NUMBER" -r $AZ_ACR_NAME --no-push .
       - wget https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_Linux-64bit.tar.gz
       - tar -xf dockle_0.3.1_Linux-64bit.tar.gz -C /usr/local/bin
       - rm dockle_0.3.1_Linux-64bit.tar.gz
       - dockle --exit-code 1 sample/sw-hello-world:"1.0.$DRONE_BUILD_NUMBER"
       
  - name: trivy image
    image: aquasec/trivy
    environment:
      <<: *tf_vars
    commands:
     # - trivy fs .
      #- trivy image --exit-code 0 --severity LOW,MEDIUM,HIGH plugins/docker:19.03.8 
     # - trivy image --exit-code 1 --severity CRITICAL plugins/docker:19.03.8 
      #- trivy image --exit-code 0 --severity LOW,MEDIUM,HIGH -f json -o results01.json plugins/docker:19.03.8 
     # - trivy image --exit-code 1 --severity CRITICAL -f json -o results02.json plugins/docker:19.03.8
  
  - name: read file
    image: ubuntu:20.04
    environment:
      <<: *tf_vars
    commands:
     # - cat results01.json
     # - cat results02.json
      
      
      
   
   
      
