kind: pipeline
name: build monitoring

environment:
  AZ_ACR_NAME: 
steps:
  - name: build image
    image: mcr.microsoft.com/azure-cli
    environment: 
      ARM_CLIENT_ID:
        from_secret: ARM_CLIENT_ID
      ARM_CLIENT_SECRET:
        from_secret: ARM_CLIENT_SECRET
      AZ_ACR_NAME:
        from_secret: AZ_ACR_NAME
      AZ_TENANT_ID:
        from_secret: AZ_TENANT_ID
      AZ_SUBSCRIPTION_ID: 
        from_secret: AZ_SUBSCRIPTION_ID
      RETRIES: 0
      MAX_RETRIES: 3
      MAJOR_VERSION: 1
      MINOR_VERSION: 0
    commands:
    - DRONE_SEMVER_MAJOR=$MAJOR_VERSION
    - DRONE_SEMVER_MINOR=$MINOR_VERSION
    - DRONE_SEMVER_PATCH=$DRONE_BUILD_NUMBER
    - DRONE_SEMVER="$DRONE_SEMVER_MAJOR.$DRONE_SEMVER_MINOR.$DRONE_SEMVER_PATCH"
    - echo $DRONE_SEMVER
    - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $AZ_TENANT_ID
    - az acr build --subscription $AZ_SUBSCRIPTION_ID -t devnetlab/devnet_lab_image:{{$DRONE_SEMVER}} -r $AZ_ACR_NAME --no-push .

