name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sw-docker-demo:1.0.1
    - name: Aqua Security Trivy
      # You may pin to the exact commit or the version.
      # uses: aquasecurity/trivy-action@2b5de510862c22b735aa586acbafe850cfe75148
      uses: aquasecurity/trivy-action@0.0.8
      with:
        # image reference
        image-ref: 'sw-docker-demo:1.0.1'
        # output format (table, json, template)
        severity: 'HIGH,CRITICAL'
        exit-code: 1
        format: 'template'
        # use an existing template for rendering output (@/contrib/sarif.tpl, @/contrib/gitlab.tpl, @/contrib/junit.tpl
        template: '@/contrib/sarif.tpl'
        # writes results to a file with the specified file name
        output: 'trivy-results.sarif'
      if: ${{ always() }}
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
      if: ${{ always() }}
